export enum ENotificacion {
    FORMATOS_FIRMADOS = 1,
    SOLICITUD_FIRMA_ASEGURADO,
    SOLICITUD_FIRMA_EJECUTIVO,
    SOLICITUD = 4,
    CONFIRMACION_ENTREGA=5,
    REVISION_DOCUMENTAL = 6,
    DATOS_CONTACTO,
    NO_CONTINUA_PROCESO,
    FIRMA_DOCUMENTOS = 13,
}